### ISSUE TITLE
Integrate Google Fonts

### ISSUE THREAD

**Issue by meherranjan** [gkubisa/elm-app-boilerplate#18]
Hi @gkubisa,

Great work on the boilerplate. 👍 
I would like to know what are your thoughts on Google Fonts integration? I also observe that https://github.com/rtfeldman/elm-spa-example/blob/master/index.html is importing it using google font CDN link.

Thanks

**Comment by gkubisa** [comment]
I'd also load them from the CDN - just paste the link tag into [html/index.html](https://github.com/gkubisa/elm-app-boilerplate/blob/master/html/index.html). If you can't use CDN for any reason, just Google how to load fonts using Webpack. Hope this helps. :+1:
