### ISSUE TITLE
Integrate routing

### ISSUE THREAD

**Issue by gkubisa** [gkubisa/elm-app-boilerplate#2]
Possibly useful modules:
- https://github.com/rgrempel/elm-route-hash
- https://github.com/TheSeamau5/elm-router

A nice perspective on routing in Elm: http://www.gizra.com/content/thinking-choosing-elm/

A sample application, which might contain some useful ideas: https://github.com/sgillis/presti

**Comment by mewben** [comment]
[https://github.com/sporto/hop](https://github.com/sporto/hop) might be good too...

**Comment by gkubisa** [comment]
Thanks for the suggestion, Melvin. I hope `hop` will support Elm 0.17 by the time I start integrating routing.

**Comment by gkubisa** [comment]
There's also https://github.com/elm-lang/navigation - just released :-)

**Comment by gkubisa** [comment]
Done: https://github.com/gkubisa/elm-app-boilerplate/releases/tag/v0.4.0
