### ISSUE TITLE
`npm run test:elm` fails

### ISSUE THREAD

**Issue by randomer** [gkubisa/elm-app-boilerplate#21]
Steps to reproduce:
1. Clone the repo
2. Run `npm install`
3. Run `npm run test:elm`

Software versions:
- **macOS** 10.12.1
- **npm** 5.5.1
- **node** v8.3.0

Terminal output:
```
> elm-app-boilerplate@0.6.0 test:elm /.../elm-app-boilerplate
> elm test --warn --compiler node_modules/.bin/elm-make elm/TestRunner.elm

I cannot find module 'Native.RunTest'.

Module 'Test.Runner.Node' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json
Compilation failed while attempting to build /.../elm-app-boilerplate/elm/TestRunner.elm
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elm-app-boilerplate@0.6.0 test:elm: `elm test --warn --compiler node_modules/.bin/elm-make elm/TestRunner.elm`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the elm-app-boilerplate@0.6.0 test:elm script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by gkubisa** [comment]
AFAIR, elm-test made a backward-incompatible change a while back, which I addressed on [update-dependencies branch](https://github.com/gkubisa/elm-app-boilerplate/tree/update-dependencies). I'm up to my ears ATM but when I get a bit of time, I'll update all the remaining dependencies and merge it into master. A PR would be welcome, too. :-)

**Comment by gkubisa** [comment]
`elm-test` dependency is now up to date and I adjusted the test setup accordingly, see https://github.com/gkubisa/elm-app-boilerplate/releases/tag/v0.6.1.
